FROM amazoncorretto:21.0.4-al2023-headless
WORKDIR /project
COPY build/libs/service-security-0.0.1-SNAPSHOT.jar /project/service-security-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "service-security-0.0.1-SNAPSHOT.jar"]

