server:
  port: 8081

app:
  name: server-shop
  password: server-shop

spring:
  application:
    name: task-user
  datasource:
    url: jdbc:postgresql://localhost:5432/ylab_shop
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    generate:
      ddl-auto: true
